const $=s=>document.querySelector(s);let map,watchId,events,manual=false,lines=[],markers={},routeCache=new Map(),searchTimer,mode='login';
const state={code:new URLSearchParams(location.search).get('meetup')||'',memberId:sessionStorage.getItem('gatherly-member')||'',token:localStorage.getItem('gatherly-token')||'',user:null,meetup:null};
const api=async(path,opts={})=>{const response=await fetch('/api/'+path,{headers:{'Content-Type':'application/json',...(state.token?{Authorization:`Bearer ${state.token}`}:{})},...opts}),body=await response.json();if(!response.ok)throw Error(body.error||'Something went wrong.');return body};
const isHost=()=>state.meetup?.leaderId===state.memberId,me=()=>state.meetup?.people.find(p=>p.id===state.memberId),invite=()=>`${location.origin}${location.pathname}?meetup=${state.code}`,fmt=n=>n>=1000?`${(n/1000).toFixed(1)} km`:`${Math.round(n)} m`,ago=s=>s?`${Math.max(0,Math.round((Date.now()-new Date(s))/1000))}s ago`:'not shared yet';
const pin=(html,size=[38,38])=>L.divIcon({html,className:'',iconSize:size,iconAnchor:[size[0]/2,size[1]]});
function authUi(){const signed=!!state.user;$('#auth-trigger').textContent=signed?`Signed in: ${state.user.name}`:'Sign in';$('#auth-trigger').disabled=signed;$('#name-input').value=signed?state.user.name:''}
function authScreen(kind='login'){mode=kind;$('#auth-title').textContent=kind==='login'?'Sign in':'Create account';$('#auth-submit').textContent=kind==='login'?'Sign in →':'Create account →';$('#auth-switch').textContent=kind==='login'?'Create an account instead':'I already have an account';$('#auth-name').parentElement.style.display=kind==='login'?'none':'grid';$('#auth-dialog').showModal()}
async function loadUser(){if(!state.token){authUi();return}try{state.user=(await api('auth/me')).user;authUi()}catch{state.token='';state.user=null;localStorage.removeItem('gatherly-token');authUi()}}
async function submitAuth(e){e.preventDefault();try{const name=$('#auth-name').value.trim(),email=$('#auth-email').value.trim(),password=$('#auth-password').value;if(!email||!password)throw Error('Enter your email and password.');if(mode==='signup'&&(!name||password.length<6))throw Error('Use a display name and a password of at least 6 characters.');const data=await api(`auth/${mode==='login'?'login':'signup'}`,{method:'POST',body:JSON.stringify({name,email,password})});state.token=data.token;state.user=data.user;localStorage.setItem('gatherly-token',data.token);authUi();$('#join-name').value=data.user.name;$('#auth-dialog').close();if(state.code)$('#join-dialog').showModal()}catch(error){alert(error.message)}}
function initMap(){map=L.map('map',{zoomControl:false,attributionControl:false}).setView([22.5665,88.3565],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);L.control.zoom({position:'topright'}).addTo(map);map.on('click',e=>manual?setLocation(e.latlng.lat,e.latlng.lng):isHost()&&saveDestination(e.latlng));}
async function loadRoutes(){if(!state.meetup)return;for(const p of state.meetup.people.filter(p=>p.sharing)){try{routeCache.set(p.id,await api(`route?from=${p.lng},${p.lat}&to=${state.meetup.destination.lng},${state.meetup.destination.lat}`))}catch{}}render()}
function route(p){const r=routeCache.get(p.id);return r?{...r,eta:Math.max(2,Math.round(r.duration/60))}:{distance:0,duration:0,eta:0}}
function render(){const m=state.meetup;if(!m||!map)return;$('#meeting-name').textContent=m.name;$('#role-label').textContent=isHost()?'Group host':'Group member';$('#account-name').textContent=state.user?.name||'';$('#destination-name').textContent=m.destination.name;$('#destination-address').textContent=m.destination.address;$('#invite-code').textContent=invite();$('#expires-time').textContent=new Date(m.expiresAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('#destination-button').style.display=isHost()?'block':'none';$('#from-status').textContent=me()?.sharing?`Live · ${ago(me().lastUpdated)}`:'Location not selected';Object.values(markers).forEach(x=>map.removeLayer(x));lines.forEach(x=>map.removeLayer(x));markers={};lines=[];markers.destination=L.marker([m.destination.lat,m.destination.lng],{icon:pin('<div class="map-pin"><span>⌖</span></div>')}).addTo(map);m.people.filter(p=>p.sharing||p.id===state.memberId).forEach(p=>{const r=route(p);markers[p.id]=L.marker([p.lat,p.lng],{icon:pin(`<div class="person-pin" style="background:${p.color}">${p.initials}</div>`,[36,36])}).addTo(map).bindPopup(`<b>${p.name}</b><br>${p.sharing?`${fmt(r.distance)} · ${r.eta||'…'} min`:'Location hidden'}`);if(p.sharing&&r.coordinates)lines.push(L.polyline(r.coordinates,{color:p.color,weight:4,opacity:.8}).addTo(map))});people()}
function people(){const all=state.meetup.people.map(p=>({p,r:route(p)})).sort((a,b)=>a.r.eta-b.r.eta),live=all.filter(x=>x.p.sharing&&x.r.eta),fast=live[0],late=live.at(-1);$('#people-count').textContent=all.length;$('#people-list').innerHTML=all.map(({p,r})=>`<div class="person"><span class="avatar" style="background:${p.color}">${p.initials}</span><div class="person-info"><div class="person-name">${p.name}${p.id===state.memberId?' (you)':''}${p.role==='leader'?' · host':''}${isHost()&&p.id!==state.memberId?` <button class="remove-member" data-id="${p.id}">Remove</button>`:''}</div><div class="person-meta">${p.sharing?`Live · ${ago(p.lastUpdated)}`:'Location sharing off'}</div></div><span class="person-time">${p.sharing&&r.eta?`${fmt(r.distance)} · ${r.eta} min`:'Private'}</span></div>`).join('');$('#group-arrival').textContent=late?`Group arrival: ${new Date(Date.now()+late.r.duration*1000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:'No live locations yet';$('#arrival-detail').textContent=fast?`Fastest: ${fast.p.name} · Latest: ${late.p.name}`:'Each member controls their visibility';$('#location-status').textContent=me()?.sharing?`Sharing live · updated ${ago(me().lastUpdated)}`:'Location sharing is off';$('#enable-location').textContent=me()?.sharing?'Live sharing is on':'Share live location';document.querySelectorAll('.remove-member').forEach(b=>b.onclick=()=>removeMember(b.dataset.id))}
function showJourney(){if(!state.meetup)return;$('#welcome').classList.add('hidden');$('#map-screen').classList.remove('hidden');if(!map)initMap();connect();render();loadRoutes()}
function connect(){events?.close();events=new EventSource(`/api/meetups/${state.code}/events?token=${encodeURIComponent(state.token)}`);events.addEventListener('meetup',e=>{const data=JSON.parse(e.data);if(data.ended){alert('This journey has ended.');return leavePage()}state.meetup=data;render();loadRoutes()})}
async function createJourney(){if(!state.user)return authScreen();const data=await api('meetups',{method:'POST',body:JSON.stringify({meetup:$('#meetup-input').value.trim()})});state.meetup=data.meetup;state.code=data.meetup.code;state.memberId=data.memberId;sessionStorage.setItem('gatherly-member',data.memberId);history.replaceState({},'',`?meetup=${state.code}`);showJourney()}
async function joinJourney(){if(!state.user)return authScreen();try{const data=await api(`meetups/${$('#join-code').value.trim().toUpperCase()}/members`,{method:'POST',body:'{}'});state.meetup=data.meetup;state.code=data.meetup.code;state.memberId=data.memberId;sessionStorage.setItem('gatherly-member',data.memberId);history.replaceState({},'',`?meetup=${state.code}`);$('#join-dialog').close();showJourney()}catch(error){alert(error.message)}}
async function updateMe(update){state.meetup=await api(`meetups/${state.code}/members`,{method:'PATCH',body:JSON.stringify({update})});render();loadRoutes()}
async function setLocation(lat,lng){manual=false;$('#manual-location').textContent='Set my location on map';await updateMe({lat,lng,sharing:true});map.setView([lat,lng],14)}
function shareLocation(){if(!navigator.geolocation)return alert('Live location is not available in this browser.');navigator.geolocation.getCurrentPosition(p=>setLocation(p.coords.latitude,p.coords.longitude),()=>alert('Location permission was not granted.'),{enableHighAccuracy:true,timeout:10000});if(watchId)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(p=>setLocation(p.coords.latitude,p.coords.longitude),()=>{},{enableHighAccuracy:true,maximumAge:5000})}
async function saveDestination(point){if(point){state.meetup.destination.lat=point.lat;state.meetup.destination.lng=point.lng}state.meetup=await api(`meetups/${state.code}/destination`,{method:'PATCH',body:JSON.stringify({destination:state.meetup.destination})});routeCache.clear();render();loadRoutes()}
async function removeMember(targetId){if(confirm('Remove this member?')){state.meetup=await api(`meetups/${state.code}/members`,{method:'DELETE',body:JSON.stringify({targetId})});render()}}
async function searchDestination(){const q=$('#destination-input').value.trim();if(q.length<3)return $('#search-results').replaceChildren();try{const places=await api(`search?q=${encodeURIComponent(q)}`);$('#search-results').innerHTML=places.map((x,i)=>`<button type="button" class="search-result" data-index="${i}">${x.name}</button>`).join('');document.querySelectorAll('.search-result').forEach(b=>b.onclick=()=>{const x=places[b.dataset.index];state.meetup.destination={name:x.name.split(',')[0],address:x.name,lat:x.lat,lng:x.lng};$('#place-name-input').value=state.meetup.destination.name;$('#address-input').value=x.name;$('#search-results').replaceChildren()})}catch{$('#search-results').textContent='Search unavailable. Choose a point on the map instead.'}}
function leavePage(){events?.close();if(watchId)navigator.geolocation.clearWatch(watchId);sessionStorage.removeItem('gatherly-member');location.href=location.pathname}
$('#start-form').onsubmit=e=>{e.preventDefault();createJourney().catch(x=>alert(x.message))};$('#join-trigger').onclick=()=>$('#join-dialog').showModal();$('#join-button').onclick=e=>{e.preventDefault();joinJourney()};$('#auth-trigger').onclick=()=>state.user?null:authScreen();$('#auth-switch').onclick=()=>authScreen(mode==='login'?'signup':'login');$('#auth-submit').onclick=submitAuth;$('#logout-button').onclick=async()=>{await api('auth/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('gatherly-token');leavePage()};$('#share-button').onclick=()=>$('#share-dialog').showModal();$('#add-friend').onclick=()=>$('#share-dialog').showModal();$('#share-close').onclick=()=>$('#share-dialog').close();$('#copy-code').onclick=async()=>{await navigator.clipboard?.writeText(invite());$('#copy-code').textContent='Copied!';setTimeout(()=>$('#copy-code').textContent='Copy link',1500)};$('#native-share').onclick=async()=>{const text=`Join my journey: ${state.meetup.name} (${state.code})\n${invite()}`;if(navigator.share)await navigator.share({title:'Gatherly journey',text,url:invite()});else{await navigator.clipboard.writeText(text);alert('Journey link copied.')}};$('#enable-location').onclick=shareLocation;$('#locate-button').onclick=shareLocation;$('#manual-location').onclick=()=>{manual=!manual;$('#manual-location').textContent=manual?'Click anywhere on the map':'Set my location on map'};$('#from-location').onclick=()=>$('#manual-location').click();$('#stop-sharing').onclick=()=>{if(watchId)navigator.geolocation.clearWatch(watchId);updateMe({sharing:false})};$('#destination-button').onclick=()=>{$('#destination-input').value='';$('#place-name-input').value=state.meetup.destination.name;$('#address-input').value=state.meetup.destination.address;$('#destination-dialog').showModal()};$('#destination-input').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(searchDestination,350)};$('#save-destination').onclick=e=>{e.preventDefault();const n=$('#place-name-input').value.trim(),a=$('#address-input').value.trim();if(n)state.meetup.destination.name=n;if(a)state.meetup.destination.address=a;$('#destination-dialog').close();saveDestination()};$('#privacy-trigger').onclick=()=>$('#privacy-dialog').showModal();$('#privacy-close').onclick=()=>$('#privacy-dialog').close();$('#demo-button').onclick=()=>alert('Share the journey link so members can join and choose whether to share location.');$('#end-meetup').onclick=async()=>{try{if(isHost()){if(!confirm('End this journey for everyone?'))return;await api(`meetups/${state.code}`,{method:'DELETE',body:'{}'})}else await api(`meetups/${state.code}/members`,{method:'DELETE',body:JSON.stringify({targetId:state.memberId})});leavePage()}catch(x){alert(x.message)}};
loadUser().then(()=>{if(state.code){$('#join-code').value=state.code;state.user?$('#join-dialog').showModal():authScreen()}});
